require_relative 'operations/update_scheduling_solution'
require_relative 'operations/update_appointment'
require_relative 'operations/update_unavailabilities'
require_relative 'operations/add_delivery'
require_relative 'operations/add_treatment'
